# Generated by Django 3.0.5 on 2021-10-06 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_auto_20211006_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='code',
            field=models.CharField(default='he', max_length=800),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 14, 47, 922248)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=800),
        ),
    ]
