# Generated by Django 3.0.5 on 2021-10-06 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_auto_20211006_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 15, 35, 647400)),
        ),
    ]
