# Generated by Django 3.0.5 on 2021-10-06 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_auto_20211006_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 16, 39, 200288)),
        ),
    ]
